# https://starship.rs/config/

# The list of modules shown on the left. Fill it with the most important modules.
format = """
$os\
$directory\
$git_branch\
$git_status\
$fill\
$status\
$cmd_duration\
$jobs\
$direnv\
$python\
$nodejs\
$nix_shell\
$time\
$newline\
$character"""

# Configuration for the newline element.
# The newline module doesn't have many configuration options,
# but you can explicitly define it if you want to fine-tune its behavior
[newline]
disabled = false

# Configuration for the prompt character.
[character]
# You can customize the prompt character based on the command status
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
vimcmd_symbol = "[â®](bold green)"

# =========================[ Module Configurations ]=========================
# Configure individual modules to match your desired appearance and information

[os]
disabled = false
style = "bold white"

[directory]
# The current directory is usually prominent
style = "bold blue"

[git_branch]
# Display the current git branch
symbol = "ï˜ "
style = "bold purple"

[git_status]
# Show git status indicators
conflicted = "ğŸ³â€ğŸŒˆ"
ahead = "ğŸï¸ğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ¤¯"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = "âœ…"
renamed = "ğŸ“›"
deleted = "ğŸ—‘ï¸"
style = "bold orange"

[status]
# Exit code of the last command
symbol = "Exit: "
format = "[$symbol$status](bold red) "
disabled = false

[cmd_duration]
# Duration of the last command
format = "[$duration](bold yellow) "
disabled = false

[jobs]
# Presence of background jobs
symbol = "âš™ï¸ "
format = "[$symbol$number](bold blue) "
disabled = false

[direnv]
# direnv status
format = "[$symbol]($style) "
symbol = "ğŸ› ï¸ "
style = "bold green"
disabled = false

[python]
# python virtual environment
symbol = "ğŸ "
format = "[$symbol($virtualenv)]($style) "
style = "bold yellow"
disabled = false

[nodejs]
# node.js version
symbol = "îœ˜ "
format = "[$symbol($version)]($style) "
style = "bold green"
disabled = false

[nix_shell]
# nix shell
symbol = "â„ï¸ "
format = "[$symbol($state)]($style) "
style = "bold blue"
disabled = false

[time]
# current time
format = "[$time](bold white) "
disabled = false

# The fill element is a spacer that pushes the elements after it to the right
[fill]
symbol = " "
